css-colors - Kyle Kettler
kyle-kettler/c0523-code-solutions pull request #33
Opened 2023-05-16 21:03 UTC by kyle-kettler

2023-05-16 21:03 UTC, kyle-kettler commented
<img width="847" alt="Screenshot 2023-05-16 at 3 49 04 PM" src="https://github.com/kyle-kettler/c0523-code-solutions/assets/126023512/e1372d0f-740b-4460-891f-77b0b93ee78e">

2023-05-16 23:17 UTC, shawnkost requested changes
A couple changes requested here Kyle!

2023-05-16 23:17 UTC, shawnkost commented on css-colors/css-colors-quiz-notes.md
> +
Don't forget the quiz questions!

2023-05-16 23:17 UTC, shawnkost commented on css-colors/styles.css
> +  background-color: rgb(244, 249, 251);
This should be applied to the `section` instead

2023-05-17 17:33 UTC, shawnkost approved these changes
👍🏻

2023-05-17 17:41 UTC, merged